// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.1
// source: processing.proto

package processing_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProcessingServiceClient is the client API for ProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessingServiceClient interface {
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error)
	ExecuteDispatch(ctx context.Context, in *ExecuteDispatchRequest, opts ...grpc.CallOption) (*ExecuteDispatchResponse, error)
}

type processingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessingServiceClient(cc grpc.ClientConnInterface) ProcessingServiceClient {
	return &processingServiceClient{cc}
}

func (c *processingServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, "/processing_v1.ProcessingService/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/processing_v1.ProcessingService/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error) {
	out := new(DeleteGroupResponse)
	err := c.cc.Invoke(ctx, "/processing_v1.ProcessingService/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingServiceClient) ExecuteDispatch(ctx context.Context, in *ExecuteDispatchRequest, opts ...grpc.CallOption) (*ExecuteDispatchResponse, error) {
	out := new(ExecuteDispatchResponse)
	err := c.cc.Invoke(ctx, "/processing_v1.ProcessingService/ExecuteDispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingServiceServer is the server API for ProcessingService service.
// All implementations must embed UnimplementedProcessingServiceServer
// for forward compatibility
type ProcessingServiceServer interface {
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	ExecuteDispatch(context.Context, *ExecuteDispatchRequest) (*ExecuteDispatchResponse, error)
	mustEmbedUnimplementedProcessingServiceServer()
}

// UnimplementedProcessingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProcessingServiceServer struct {
}

func (UnimplementedProcessingServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedProcessingServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedProcessingServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedProcessingServiceServer) ExecuteDispatch(context.Context, *ExecuteDispatchRequest) (*ExecuteDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteDispatch not implemented")
}
func (UnimplementedProcessingServiceServer) mustEmbedUnimplementedProcessingServiceServer() {}

// UnsafeProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessingServiceServer will
// result in compilation errors.
type UnsafeProcessingServiceServer interface {
	mustEmbedUnimplementedProcessingServiceServer()
}

func RegisterProcessingServiceServer(s grpc.ServiceRegistrar, srv ProcessingServiceServer) {
	s.RegisterService(&ProcessingService_ServiceDesc, srv)
}

func _ProcessingService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processing_v1.ProcessingService/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessingService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processing_v1.ProcessingService/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessingService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processing_v1.ProcessingService/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessingService_ExecuteDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServiceServer).ExecuteDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processing_v1.ProcessingService/ExecuteDispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServiceServer).ExecuteDispatch(ctx, req.(*ExecuteDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessingService_ServiceDesc is the grpc.ServiceDesc for ProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processing_v1.ProcessingService",
	HandlerType: (*ProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _ProcessingService_CreateGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _ProcessingService_ListGroups_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _ProcessingService_DeleteGroup_Handler,
		},
		{
			MethodName: "ExecuteDispatch",
			Handler:    _ProcessingService_ExecuteDispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processing.proto",
}
